function runfig_mAP_vs_it(dataset, varargin)
	if strcmp(dataset, 'cifar')
		ntrain = 20e3;
		metric = 'mAP';
		U = 50;
		T = 5;
		adaptA = 0.9;  adaptB = 0.01;  adaptS = 0.25;
		okhC = 1;  okhA = 0.1;
		sketchsize = 200;
		lambda = 0.25;
	else
		assert(strcmp(dataset, 'places'));
		ntrain = 40e3;
		metric = 'prec_n3';
		U = 100;
		T = 3;
		adaptA = 0.75;  adaptB = 0.01;  adaptS = 0.1;
		okhC = 1;  okhA = 0.1;
		sketchsize = 100;
		lambda = 0.01;
	end

	% AdaptHash
	demo_adapthash('cnn', dataset, 32, 'noTrainingPoints', ntrain, 'ntests', 20, ...
		'ntrials', T, 'metric', metric, 'showplots', 0, ...
		'updateInterval', U, ...
		'alpha', adaptA, 'beta', adaptB, 'stepsize', adaptS, ...
		varargin{:});

	% OECC
	demo_osh('cnn', dataset, 32, 'noTrainingPoints', ntrain, 'ntests', 20, ...
		'ntrials', T, 'metric', metric, 'showplots', 0, ...
		'updateInterval', U, ...
		'SGDBoost', 1, ...
		varargin{:});

	% OKH
	demo_okh('cnn', dataset, 32, 'noTrainingPoints', ntrain, 'ntests', 20, ...
		'ntrials', T, 'metric', metric, 'showplots', 0, ...
		'updateInterval', U, ...
		'c', okhC, 'alpha', okhA, ...
		varargin{:});

	% SketchHash
	demo_sketch('cnn', dataset, 32, 'noTrainingPoints', ntrain, 'ntests', 20, ...
		'ntrials', T, 'metric', metric, 'showplots', 0, ...
		'onlyfinal', 0, 'sketchsize', sketchsize, 'batchsize', U, ...
		varargin{:});

	% Ours
	demo_osh('cnn', dataset, 32, 'noTrainingPoints', ntrain, 'ntests', 20, ...
		'ntrials', T, 'metric', metric, 'showplots', 0, ...
		'updateInterval', U, ...
		varargin{:});

	% Ours-dyn
	demo_osh('cnn', dataset, 32, 'noTrainingPoints', ntrain, 'ntests', 20, ...
		'ntrials', T, 'metric', metric, 'showplots', 0, ...
		'adaptive', 1, 'reg_rs', lambda, ...
		varargin{:});
end
