% for getting the final results in Table 2
%
demo_adapthash('cnn', 'places', 12, 'noTrainingPoints', 100e3, 'ntests', 2, ...
	'update_interval', 100e3, 'labelspercls', 0, 'override', 0, ...
	'alpha', 0.9, 'stepsize', 0.3, 'metric', 'prec_n3', 'ntrials', 3, 'showplots', 0)

demo_adapthash('cnn', 'places', 24, 'noTrainingPoints', 100e3, 'ntests', 2, ...
	'update_interval', 100e3, 'labelspercls', 0, 'override', 0, ...
	'alpha', 0.9, 'stepsize', 0.1, 'metric', 'prec_n3', 'ntrials', 3, 'showplots', 0)

demo_adapthash('cnn', 'places', 32, 'noTrainingPoints', 100e3, 'ntests', 2, ...
	'update_interval', 100e3, 'labelspercls', 0, 'override', 0, ...
	'alpha', 0.75, 'stepsize', 0.1, 'metric', 'prec_n3', 'ntrials', 3, 'showplots', 0)

demo_adapthash('cnn', 'places', 64, 'noTrainingPoints', 100e3, 'ntests', 2, ...
	'update_interval', 100e3, 'labelspercls', 0, 'override', 0, ...
	'alpha', 0.8, 'stepsize', 0.25, 'metric', 'prec_n3', 'ntrials', 3, 'showplots', 0)
