function [net, imageSize, normalize] = vggf(opts)

imageSize = 224;
normalize = false;

net = load(fullfile(opts.localDir, 'models', 'imagenet-vgg-f.mat'));
net.layers(end) = [];
net.layers(end) = [];

% FC layer
net.layers{end+1} = struct('type', 'conv', ...
    'name'         , 'logits'        , ...
    'weights'      , {Models.init_weights(1, 4096, opts.nbits)} , ...
    'learningRate' , [1 1]           , ...
    'stride'       , 1               , ...
    'pad'          , 0 );

% loss layer
net.layers{end+1} = struct('type', 'custom', ...
    'name'     , 'loss'          , ...
    'weights'  , []              , ...
    'precious' , false           , ...
    'opts'     , opts            , ...
    'forward'  , @mi_forward     , ...
    'backward' , @mi_backward );

net = vl_simplenn_tidy(net);

end
